# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3


events = [('1651651651', 'Bakdaulet Bolat', 'Вышел'),
        ('1651651651', 'Bakdaulet Bolat', 'Вход'),
        ('1651651651', 'Bakdaulet Bolat', 'Вышел'),
        ('6468468466', 'Djars', 'Вышел'),
        ('6468468466', 'Djars', 'Вход'),
        ('6541651650', 'Nurbek', 'Вышел')]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 801, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 801, 481))
        self.groupBox.setObjectName("groupBox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.eventMain = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.eventMain.setObjectName("eventMain")
        self.horizontalLayout.addWidget(self.eventMain)
        self.sendBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout.addWidget(self.sendBtn)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.sendBtn.clicked.connect(self.clicked)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.con = sqlite3.connect("mydb.db") 
        self.cursor = self.con.cursor()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def createBase(self):
        try:
            self.cursor.execute("""CREATE TABLE events
                    (id INTEGER PRIMARY KEY,f_iin text, f_fio text,
                    f_event text)
                """)
            self.con.commit()
        except sqlite3.OperationalError:
            print('Уже сущетвует')

    def collectData(self):
        self.cursor.execute("SELECT * FROM events;")
        one_result = self.cursor.fetchall()
       
       
        
    def createData(self):
        self.cursor.executemany("INSERT INTO events VALUES (NULL,?,?,?)", events)

    def clicked(self):
        self.collectData()
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.createBase()
    ui.createData()
    MainWindow.show()
    sys.exit(app.exec_())
